# Generated by Django 4.0.6 on 2022-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imageLink', models.CharField(max_length=50)),
                ('ratings', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('merchantName', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
