# Generated by Django 4.0.6 on 2022-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0002_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='productLink',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='imageLink',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='ratings',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
