# Generated by Django 4.0.6 on 2022-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0006_remove_productdetails_new22'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='latestNew',
            field=models.CharField(default='90', max_length=50),
        ),
    ]
