# Generated by Django 4.0.6 on 2022-08-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0008_remove_productdetails_latestnew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='new',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
