# Generated by Django 4.0.6 on 2022-08-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0009_productdetails_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='new',
        ),
    ]
