# Generated by Django 4.0.6 on 2022-08-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0003_productdetails_productlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='new',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
