# Generated by Django 4.0.6 on 2022-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0004_productdetails_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='new22',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
