# Generated by Django 4.0.6 on 2022-08-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0005_productdetails_new22'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='new22',
        ),
    ]
