# Generated by Django 4.0.6 on 2022-08-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0007_productdetails_latestnew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='latestNew',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='new',
        ),
    ]
