# Generated by Django 4.0.6 on 2022-08-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Haggle', '0011_alter_productdetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='slug',
            field=models.SlugField(editable=False, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
