# Generated by Django 4.0.6 on 2022-09-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Haggle', '0012_productdetails_slug_alter_productcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='merchantLogo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
